version: "3"
services:
  selenium-hub:
    image: selenium/hub:3.141.59
    container_name: selenium-hub
    ports:
      - "4444:4444"
    expose:
      - 4444
  chrome:
    image: selenium/node-chrome:3.141.59
    container_name: chrome
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  firefox:
    image: selenium/node-firefox:3.141.59
    container_name: firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  tests:
    image: onlinerby-test-framework
    container_name: onliner-ui-tests
    depends_on:
      - chrome
      - firefox
    environment:
      - INSIDE_CONTAINER=true
      - SELENIUM_HUB=http://selenium-hub:4444/wd/hub
      - USERNAME='USERNAME'
      - PASSWORD='PASSWORD'
